### ISSUE TITLE
Cordova q not supported

### ISSUE THREAD

**Issue by Arthi22** [appfeel/cordova-play-services-version-adapter#3]
"requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by Djehouti** [comment]
Hey there I've got the same issue , have you found a work around ?

**Comment by 50l3r** [comment]
Same problem

**Comment by 50l3r** [comment]
https://github.com/appfeel/cordova-play-services-version-adapter/issues/2

**Comment by bchellingworth** [comment]
Same problem here. This plugin was supposed to fix my build errors, instead it just added more

**Comment by appfeel** [comment]
fixed in v1.1.0 (published in npm)
