### ISSUE TITLE
How to make it same play service version

### ISSUE THREAD

**Issue by Arthi22** [appfeel/cordova-play-services-version-adapter#4]
You have an incompatibility of versions with the following dependencies of 'Google Play Services':
    - 'com.google.android.gms:play-services-ads:15.0.0'
    - 'com.google.android.gms:play-services-base:11.0.4'
    - 'com.google.android.gms:play-services-ads:11.0.4'
    - 'com.google.firebase:firebase-analytics:15.0.0'
    - 'com.google.android.gms:play-services-tagmanager:+'
    - 'com.google.firebase:firebase-core:+'
    - 'com.google.firebase:firebase-messaging:+'
    - 'com.google.firebase:firebase-config:+'
    - 'com.google.firebase:firebase-perf:+

**Comment by Juanperezc** [comment]
Same issue cordova-fcm-plugin

**Comment by appfeel** [comment]
The purpose of this plugin is to find if there is a compatibility available, and when there it is, apply it. Otherwise you should try to compile anyway (may work sometimes) or find plugin versions that use the compatible google play versions. It's hard!
