### ISSUE TITLE
Not solving problem compability

### ISSUE THREAD

**Issue by pedroayres** [appfeel/cordova-play-services-version-adapter#6]
'Cordova Play Services Version Adapter' has detected an error. The following dependencies of 'Google Play Services' are not compatible:
You have an incompatibility of versions with the following dependencies of 'Google Play Services':
    - 'com.google.android.gms:play-services-tagmanager:+'
    - 'com.google.firebase:firebase-core:+'
    - 'com.google.firebase:firebase-messaging:+'
    - 'com.google.firebase:firebase-config:+'
    - 'com.google.firebase:firebase-perf:+'
    - 'com.google.android.gms:play-services-gcm:15+'

It doesn't exists a version of 'Google Play Services' that includes all these dependencies.
All dependencies of 'Google Play Services' must have the same version.
The application may not compile.

**Comment by moblizeit** [comment]
same not resoliving me for errors below
cordova-android-support-gradle-release: No custom version found in package.json - using plugin default

'Cordova Play Services Version Adapter' has detected an error. The following dependencies of 'Google Play Services' are not compatible:
You have an incompatibility of versions with the following dependencies of 'Google Play Services':
    - 'com.google.android.gms:play-services-ads:15.0.0'
    - 'com.google.android.gms:play-services-tagmanager:+'
    - 'com.google.firebase:firebase-core:+'
    - 'com.google.firebase:firebase-messaging:+'
    - 'com.google.firebase:firebase-config:+'
    - 'com.google.firebase:firebase-perf:+'
    - 'com.google.android.gms:play-services-auth:11.8.0'
    - 'com.google.android.gms:play-services-identity:11.8.0'

It doesn't exists a version of 'Google Play Services' that includes all these dependencies.
All dependencies of 'Google Play Services' must have the same version.
The application may not compile.

**Comment by dsilvestregil** [comment]
Hey moblizeit!

I have a possible solution to you, edit your 'platforms/android/project.properties' file, and try to set this versions:
    - 'com.google.android.gms:play-services-ads:15.0.0'
    - 'com.google.android.gms:play-services-tagmanager:15.0.0'
    - 'com.google.firebase:firebase-core:15.0.0'
    - 'com.google.firebase:firebase-messaging:15.0.0'
    - 'com.google.firebase:firebase-config:15.0.0'
    - 'com.google.firebase:firebase-perf:15.0.0'
    - 'com.google.android.gms:play-services-auth:15.0.0'
    - 'com.google.android.gms:play-services-identity:15.0.0'

The next packages are not included on this version adapter plugin, you need to adapt the version manually:
    - 'com.google.firebase:firebase-core'
    - 'com.google.firebase:firebase-perf'

**Comment by appfeel** [comment]
see #4
